### PR TITLE
Do not prefix timestamps from runit

### PR DESCRIPTION
**Pull request by rmarianski**
Connects to https://github.com/mapzen/chef-mapzen_tapalcatl/pull/2

### CODE REVIEW

**Comment by zerebubuth** [comment]
I tried running the kitchen tests and it failed (I think unrelated to this PR), but the log lines still seem to have the double timestamp in them:

```
2017-03-07_17:08:49.13819 2017/03/07 17:08:49.138178 {"category":"config","hostname":"default-ubuntu-1404","message":"S3 storage missing bucket configuration","type":"error"}
```

**Comment by rmarianski** [comment]
Yea, I was optimistic when creating this pr, and when I tried it on the server it is also logging two timestamps. I'll continue to dig into how this can be done with runit.

**Comment by zerebubuth** [comment]
Great! That seems to have fixed it.

**Comment by rmarianski** [comment]
Ok, with that latest change it worked on the server for a new instance, but not running setup on an existing one.

**Comment by zerebubuth** [comment]
Is there something that isn't getting `SIGHUP`ped that needs to be?

**Comment by rmarianski** [comment]
`sv exit` followed by `sv start` worked. The `svlogd` process needed to be restarted.

**Pull request merged**
